import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { WorkflowCanvas } from "@/components/WorkflowCanvas";
import { NodeInspector } from "@/components/NodeInspector";
import { supabase } from "@/lib/supabase";
import { validateWorkflowDoc } from "@/lib/workflow";
import { simulateWorkflow } from "@/lib/simulate";
import { useWorkflowStore } from "@/stores/workflowStore";

const DEMO_PROMPTS = [
  "When a new client intake form is submitted, summarize the needs, categorize the request, and save the structured data.",
  "When I upload meeting notes, extract action items, assign priorities, and generate a checklist.",
  "When a new lead is received, score lead quality 1–10, tag industry, and mark high-quality leads for priority follow-up.",
];

export function WorkflowNewPage() {
  const [prompt, setPrompt] = useState(DEMO_PROMPTS[0]);
  const [name, setName] = useState("New Workflow");
  const [description, setDescription] = useState("Generated by Vyntra");
  const [tags, setTags] = useState("va");
  const [errors, setErrors] = useState<string[]>([]);
  const [status, setStatus] = useState<string | null>(null);

  const { current, setWorkflow, selectedNodeId, setSelectedNodeId } = useWorkflowStore();
  const nav = useNavigate();

  async function readFunctionError(error: unknown): Promise<string[]> {
    const fallback = error instanceof Error ? error.message : "Failed to generate workflow.";
    const response = (error as { context?: Response } | null)?.context;
    if (!response) return [fallback];

    try {
      const payload = await response.clone().json();
      if (Array.isArray(payload?.details)) {
        return payload.details.map((d: { path?: string[]; message?: string }) =>
          `${(d.path ?? []).join(".")}: ${d.message ?? "Validation error"}`,
        );
      }
      if (typeof payload?.error === "string") return [payload.error];
    } catch {
      try {
        const text = await response.clone().text();
        if (text) return [text];
      } catch {
        return [fallback];
      }
    }

    return [fallback];
  }

  async function generate() {
    setStatus("Generating workflow...");
    setErrors([]);

    const { data: userData, error: userError } = await supabase.auth.getUser();
    if (userError || !userData.user) {
      setStatus(null);
      setErrors(["You must be signed in to generate workflows."]);
      return;
    }

    const { data, error } = await supabase.functions.invoke("generate-workflow", {
      body: { prompt, name, description, tags: tags.split(",").map((t) => t.trim()).filter(Boolean) },
    });

    if (error) {
      setStatus(null);
      setErrors(await readFunctionError(error));
      return;
    }

    if (!data?.ok) {
      setStatus(null);
      if (Array.isArray(data?.details)) {
        setErrors(data.details.map((d: { path?: string[]; message?: string }) => `${(d.path ?? []).join(".")}: ${d.message ?? "Validation error"}`));
      } else {
        setErrors([data?.error ?? "Failed to generate workflow."]);
      }
      return;
    }

    const parsed = validateWorkflowDoc(data?.workflow_doc);
    if (!parsed.ok) {
      setStatus(null);
      setErrors(parsed.errors);
      return;
    }

    setWorkflow(parsed.data);
    setStatus("Workflow generated.");
  }

  async function save() {
    if (!current) return;

    const check = validateWorkflowDoc(current);
    if (!check.ok) {
      setErrors(check.errors);
      return;
    }

    const { data: userData } = await supabase.auth.getUser();
    const userId = userData.user?.id;
    if (!userId) return;

    const { data, error } = await supabase
      .from("workflows")
      .insert({
        user_id: userId,
        name,
        description,
        prompt,
        tags: tags.split(",").map((t) => t.trim()).filter(Boolean),
        definition_json: check.data,
      })
      .select("id")
      .single();

    if (error) return setErrors([error.message]);
    nav(`/app/workflows/${data.id}`);
  }

  async function simulate() {
    if (!current) return;
    const check = validateWorkflowDoc(current);
    if (!check.ok) return setErrors(check.errors);

    const result = simulateWorkflow(check.data);
    setStatus(`Simulation completed (unsaved workflow): ${result.status}`);
  }

  return (
    <div className="space-y-4">
      <h1 className="text-2xl font-semibold">New Workflow</h1>
      <div className="grid gap-4 xl:grid-cols-[320px_1fr_320px]">
        <Card className="space-y-3">
          <Input value={name} onChange={(e) => setName(e.target.value)} placeholder="Workflow name" />
          <Input value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Description" />
          <Input value={tags} onChange={(e) => setTags(e.target.value)} placeholder="tags comma-separated" />
          <Textarea rows={8} value={prompt} onChange={(e) => setPrompt(e.target.value)} placeholder={DEMO_PROMPTS[0]} />
          <div className="space-y-1">
            {DEMO_PROMPTS.map((p) => (
              <button key={p} className="w-full rounded border p-2 text-left text-xs" onClick={() => setPrompt(p)}>
                {p}
              </button>
            ))}
          </div>
          <div className="flex flex-wrap gap-2">
            <Button onClick={generate}>Generate</Button>
            <Button variant="outline" onClick={simulate} disabled={!current}>Test Workflow</Button>
            <Button variant="outline" onClick={save} disabled={!current}>Save</Button>
          </div>
          {status && <p className="text-sm text-slate-600">{status}</p>}
          {errors.length > 0 && <pre className="overflow-auto text-xs text-red-700">{errors.join("\n")}</pre>}
        </Card>

        <div>
          {current ? (
            <WorkflowCanvas doc={current} onSelectNode={setSelectedNodeId} />
          ) : (
            <Card className="h-[600px] text-sm text-slate-500">Generate a workflow or start from template.</Card>
          )}
        </div>

        <div>
          <NodeInspector key={selectedNodeId ?? "none"} />
        </div>
      </div>
    </div>
  );
}
